<a href="https://colab.research.google.com/github/MikeRuz551/PythonDA/blob/main/%2202hw_numpy_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np
np.__version__

2) Создать нулевой вектор размера 10

In [ ]:
np.zeros(10, dtype=int)

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
np.full(7,7)

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
np.arange(10,101,2)

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
np.random.randn(3,3)[::-1]

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
np.arange(9).reshape((3,3))

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
np.eye(4, k=1, dtype=int)

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [14]:
7 - np.identity(4, dtype=int) * 7 + np.diag([i for i in range(1, 5)])

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [17]:
arr = np.zeros((5,5),dtype=int)
arr + np.arange(5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [21]:
arr=np.random.randn (10,10)
arr-np.mean (arr,axis=1, keepdims=True)

array([[ 1.68729081, -0.11642709,  0.71679477,  0.0626736 , -1.4405278 ,
         0.48232124, -0.44030875, -0.33761453,  0.5660252 , -1.18022744],
       [ 0.36937017, -0.3927015 , -0.14083809, -0.38465557, -0.32305342,
        -1.51899937, -0.15441993,  1.91522815,  0.60780479,  0.02226477],
       [ 0.72464892,  1.41095095, -0.55282575,  1.74285162, -1.96703426,
         0.13150754,  0.68885155,  0.18063502, -0.55047252, -1.80911308],
       [ 1.37677311,  1.15617781, -0.08082384, -0.46539415, -0.43938875,
        -0.36167646, -1.31245351,  0.40986874,  0.09366938, -0.37675234],
       [-0.88129022, -0.81912577,  1.04645353, -0.38382113,  0.84302585,
        -0.22407924,  1.70060409, -1.96661646,  0.59569781,  0.08915155],
       [-0.14792744, -0.52711461,  2.48970456,  0.25579665, -1.0403793 ,
        -1.64375791, -0.2869105 , -0.66900691, -0.41378717,  1.98338262],
       [ 1.24844067, -0.07578852, -0.74709903, -1.53451129,  0.60574025,
        -0.71851942,  1.0668201 , -0.60541129

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
arr=np.random.randn(10,10)
arr-np.median (arr, axis=0)


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [27]:
arr=np.random.randn(5,5)
np.concatenate((arr, np.max(arr, axis=1,keepdims=True),np.min(arr, axis=1,keepdims=True)),axis=1)

array([[-1.45874056,  0.22275952, -0.72485403, -0.71860623,  0.97835371,
         0.97835371, -1.45874056],
       [ 0.69061199, -0.80638094, -0.74543069, -0.66568672, -1.96580527,
         0.69061199, -1.96580527],
       [-0.26604984,  0.28532221, -0.53465862, -2.14037455, -0.76035246,
         0.28532221, -2.14037455],
       [-0.75403076,  0.07930791, -2.13882042,  0.78382282,  1.77521331,
         1.77521331, -2.13882042],
       [ 0.68873013,  1.19368975,  0.28994046,  0.18511593,  1.52079714,
         1.52079714,  0.18511593]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [28]:
arr=np.arange(1,51)
odd=arr[::2].reshape(5,5)
even=arr[1::2].reshape(5,5)
np.linalg.inv(np.matml(odd,even))

AttributeError: ignored

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [32]:
arr=np.zeros((8,8),dtype=int)
arr[::2,::2]=1
arr[1::2,1::2]=1
arr

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])